instam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#importing index from photo app
from photo_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',index) #specifying path from view
    path('',include('photo_app.urls')),
    path('user/',include('user_app.urls')),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo_app/urls.py
from django.contrib import admin
from django.urls import path

#importing index from photo app
from photo_app.views import index, add, edit, profile, delete, search
app_name = 'photo_app' 

urlpatterns = [
    
    #path('',index) #specifying path from view
    path('search/',search, name='search'),
    path('',index, name='index'),
    path('add',add,name='add'),
    path('profile/',profile,name='profile'),
    path('edit/<int:id>/',edit,name='edit'),
    path('delete/<int:id>/',delete,name='delete'),
]

user_app/urls.py
from django.contrib import admin
from django.urls import path

#importing index from photo app
from .views import display, index, loginauth,logout

app_name = 'user'
urlpatterns = [
    #path('',index) #specifying path from view
    # path('display/', display),
     path('login/', loginauth, name='login'),
     path('logout/', logout,name='logout')
]

photo_app/models.py
from django.db import models
from user_app.models import UserModel

# Create your models here.
class PhotoModel(models.Model):
    photo = models.ImageField(upload_to='upload_pic')
    caption = models.TextField(blank=True,null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='uploaded_posts')
    likes = models.PositiveIntegerField(default=0)
    

class CommentModel(models.Model):
    comment = models.TextField(blank=True,null=True)
    ctimestamp = models.DateTimeField(auto_now_add=True)
    commented_by = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='comments')
    parent_post = models.ForeignKey(PhotoModel, on_delete=models.CASCADE, related_name='comments')

user_app/models.py
from django.db import models

# Create your models here.
class UserModel(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=20,unique=True)
    password = models.CharField(max_length=255)
    email = models.EmailField()
    bio = models.TextField()
    photo = models.ImageField(upload_to='profile_pic')

    def __str__(self):
        return self.username

photo_app/forms.py
from django import forms
from .models import PhotoModel,CommentModel

class PhotoForm(forms.ModelForm):
    class Meta:
        model = PhotoModel
        fields = '__all__'
        #fields = ()'photo','comment') #for specific

class CommentForm(forms.ModelForm):
    class meta:
        model = CommentModel
        fields = '__all__'

photo_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import PhotoModel
from .models import CommentModel
from .forms import PhotoForm
from user_app.models import UserModel

# Create your views here.
def index(request):
    if 'id' in request.session:
        upload = PhotoModel.objects.all()
        #comment = CommentModel.objects.all()
        return render(request,'photo_app/index.html',{'upload':upload,})#'comment':comment
    else:
        return redirect('user:login')    

def profile(request):
    if 'id' in request.session:
        user_id = request.session['id']
        upload = PhotoModel.objects.filter(uploaded_by = user_id)
        user = UserModel.objects.get(id = user_id)
        dict = {'upload': upload,'user': user}
        return render(request,'photo_app/profile.html',dict)
    else:
        return redirect('user:login')    
        

def add(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('photo_app:index')
            except:
                return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not valid')    
    else:    
        form = PhotoForm
        return render(request,'photo_app/addphoto.html',{'form':form})

def edit(request,id):
    photo = PhotoModel.objects.get(id=id)
    if request.method == 'POST':
        form = PhotoForm(request.POST,request.FILES,instance=photo)
             
        if form.is_valid():
            try:
                form.save()
                return redirect('photo_app:index')
            except:
                return HttpResponse('Failed')
        else:
            print(form.errors)
            return HttpResponse('Form not valid')    
    else:    
        # form = PhotoForm
        return render(request,'photo_app/edit_photo.html',{'photo':photo})
    
def delete(request,id):
    photo = PhotoModel.objects.get(id=id)
    photo.delete()
    return redirect('photo_app:profile')

def search(request):
    if 'id' not in request.session:
        return redirect('user:login')

    userid = request.session.get('id',None)

    if request.method == 'GET':
        query = request.GET.get('q',None)
        if query:
            d = {
                'profiles' : UserModel.objects.filter(username__icontains=query).exclude(id=userid),
                'query' : query
            }    
            return render(request,'photo_app/search_results.html',d)
        else:
            return redirect('photo_app:index')
    else:
        return redirect('photo_app:index')
    

user_app/views.py
from django.shortcuts import render,redirect
from .models import  UserModel
from django.http import HttpResponse

# Create your views here.
def display(request):
    return render(request,'user_app/display.html') #render template

def index(request):
    return render(request,'user_app/index.html') #render template

def loginauth(request):
      
    if request.method == "POST":
        e = request.POST.get('email')
        p = request.POST.get('pass')

        user = UserModel.objects.filter(email=e,password=p)

        if(user.count()>0):
            for user in user:
                request.session['email'] = user.email
                request.session['id'] = user.id 
                request.session['username'] = user.username 
                return redirect ('photo_app:index')

        else:
            return HttpResponse('Wrong Credentials')


    else:
        return render(request, 'login.html')  


def logout(request):
    request.session.flush()
    return redirect ('user:login')

photo_app/templates/photo_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Feed | Instaclone</title>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link href="{% static 'css/style.css'%}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    </head> 
    <body>
        <nav class="navigation">
            <a href="feed.html">
                <img 
                    src="{% static 'images/navLogo.png'%}"
                    alt="logo"
                    title="logo"
                    class="navigation__logo"
                />
            </a>
            <div class="navigation__search-container">
                <i class="fa fa-search"></i>
                <form action="{% url 'photo_app:search' %}" method="GET">
                     <input id="search-bar" type="text" placeholder="Search" name="q">
                 </form>
            </div>
            <div class="navigation__icons">
                <a href="explore.html" class="navigation__link">
                    <i class="fa fa-compass"></i>
                </a>
                <a href="#" class="navigation__link">
                    <i class="fa fa-heart-o"></i>
                </a>
                <a href="{% url 'photo_app:profile'%}" class="navigation__link">
                    <i class="fa fa-user-o"></i>
                </a>
            </div>
        </nav>
        
        {% block main_content %}
          write your block 
        {% endblock %}      

        <footer class="footer">
            <nav class="footer__nav">
                <ul class="footer__list">
                    <li class="footer__list-item"><a href="#" class="footer__link">about us</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">support</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">blog</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">press</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">api</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">jobs</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">privacy</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">terms</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">directory</a></li>
                    <li class="footer__list-item"><a href="#" class="footer__link">language</a></li>
                </ul>
            </nav>
            <span class="footer__copyright">© 2019 instagram</span>
        </footer>
        <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
        <script src="{% static 'js/app.js'%}"></script>

        <!-- {% block javascript %}

        {% endblock %} -->
    </body>
</html>

photo_app/templates/photo_app/index.html
{% extends 'photo_app/base.html' %}
{% load static %}

{% block main_content %}

    <main class="feed">

        {% for up in upload %}
            <section class="photo">
            <header class="photo__header">
                <div class="photo__header-column">
                    <img
                        class="photo__avatar"
                        src="{{up.uploaded_by.photo.url}}"
                    />
                </div>
                <div class="photo__header-column">
                    <span class="photo__username">{{up.uploaded_by.username}}</span>
                    <span class="photo__location">{{up.caption}}</span>
                </div>
            </header>
            <div class="photo__file-container">
                <img
                    class="photo__file"
                    src="{{up.photo.url}}"
                />
            </div>
            <div class="photo__info">
                <div class="photo__icons">
                    <span class="photo__icon">
                        <i class="fa fa-heart-o heart fa-lg"></i>
                    </span>
                    <span class="photo__icon">
                        <i class="fa fa-comment-o fa-lg"></i>
                    </span>
                </div>
                <span class="photo__likes">{{up.comments.all|length}} galler{{up.comments.all|pluralize:"y,ies"}} </span>
                <ul class="photo__comments">
    
                    {% for comment in up.comments.all|slice:":2" %}
                        <li class="photo__comment">
                            <span class="photo__comment-author">{{comment.commented_by.username}}</span>{{comment.comment}}
                        </li>
                    {% endfor%}
                    
                </ul>
                <span class="photo__time-ago">{{up.timestamp}}</span>
                <div class="photo__add-comment-container">
                    <textarea placeholder="Add a comment..." class="photo__add-comment"></textarea>
                    <i class="fa fa-ellipsis-h"></i>
                </div>
            </div>
            </section>
        {% endfor%}
    </main>

{% endblock %}

<!-- {% block javascript %}


onmouseover="increase()" onmouseout="decrease()" id="img1"
<script type="text/javascript">
    
    var width=100
    var difference=2
    var intervalID=0

    function increase()
    {
        clearInterval(intervalID);
        intervalID = setInterval(zoomIn,20);
    }
    function zoomIn()
    {
        if (width<200)
        {
            width = width + difference;
            document.getElementById('img1').style.width=width;
        }
        else
        {
            clearInterval(intervalID);
        }
    }

    function decrease)
    {
        clearInterval(intervalID);
        intervalID = setInterval(zoomOut,20);
    }
    function zoomOut()
    {
        if (width>100)
        {
            width = width - difference;
            document.getElementById('img1').style.width=width;
        }
        else
        {
            clearInterval(intervalID);
        }
    }
   </script>

{% endblock %} -->

photo_app/templates/photo_app/profile.html
{% extends 'photo_app/base.html' %} 

{% load static %}
{% block main_content %} 
<main class="profile-container">
    <section class="profile">
        <header class="profile__header">
            <div class="profile__avatar-container">
                <img 
                    src="{{user.photo.url}}"
                    class="profile__avatar"
                />
            </div>
            <div class="profile__info">
                <div class="profile__name">
                    <h1 class="profile__title">serranoarevalo</h1>
                    <a href="edit-profile.html" class="profile__button u-fat-text">Edit profile</a>
                    <i class="fa fa-cog fa-2x" id="cog"></i>
                </div>
                <ul class="profile__numbers">
                    <li class="profile__posts">
                        <span class="profile__number u-fat-text">{{user.uploaded_posts.all|length}}</span> posts
                    </li>
                    <li class="profile__followers">
                        <span class="profile__number u-fat-text">40</span> followers
                    </li>
                    <li class="profile__following">
                        <span class="profile__number u-fat-text">134</span> following
                    </li>
                </ul>
                <div class="profile__bio">
                    <span class="profile__full-name u-fat-text">Nicolás Serrano Arévalo</span>
                    <p class="profile__full-bio">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit rerum consequuntur aperiam, dicta delectus nihil voluptas explicabo sapiente quisquam. Eius ipsam asperiores excepturi maiores, atque voluptatum sed fuga esse molestiae.</p>
                    <a href="http://serranoarevalo.com" class="profile__link u-fat-text">serranoarevalo.com</a>
                </div>
            </div>
        </header>
        <div class="profile__pictures">
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
            <a href="image-detail.html" class="profile-picture">
                <img
                    src="images/feedPhoto.jpg"
                    class="profile-picture__picture"
                />
                <div class="profile-picture__overlay">
                    <span class="profile-picture__number">
                        <i class="fa fa-heart"></i> 450
                    </span>
                    <span class="profile-picture__number">
                        <i class="fa fa-comment"></i> 39
                    </span>
                </div>
            </a>
        </div>
    </section>
</main>

{% endblock %}

photo_app/templates/photo_app/search_results.html
{% extends 'photo_app/base.html'%}
{% block main_content%}

 <main class="explore">
            <section class="people">
                <ul class="people__list">
                    {% for user in profiles%}
                    <li class="people__person">
                        <div class="people__column">
                            <div class="people__avatar-container">
                                <img 
                                    src="{{user.photo.url}}"
                                    class="people__avatar"
                                />
                            </div>
                            <div class="people__info">
                                <span class="people__username">{{user.username}}</span>
                                <span class="people__full-name">{{ user.name }}</span>
                            </div>
                        </div>
                        <div class="people__column">
                            <a href="#">Follow</a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        </main>
 
{% endblock %}        

user_app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel='stylesheet' href="{% static 'css/style.css' %}">
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login </title>
</head>
<body>
    <div class="row">

        <form action="" method="POST">
            {% csrf_token %}
        <div class="login text-center">
        <h1 style="color: rgb(97, 97, 236);">Login</h1></div><br>
       Email <br>
      <input type="text" class="form-control" name="email" style="margin-left: 40px">
      <br>
      Password:<br>
      <input type="password" class="form-control" name="pass" style="margin-left: 40px">
      <!-- <small><a href="#">Forgot password</a></small> -->
      <br><br>
      <button type="submit" name="login" class="btn btn-success" style="display: inline-block;
      padding: 10px 30px;
      border-radius: 200px;
      background-color:#f39d12;
      border: 1px #f39c12;" >Login</button>
      
    </form>
</div>
</body>
</html>

user_app/templates/user_app/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Hello. You are a User</h2>
</body>
</html>